### ISSUE TITLE
Running server in embedded causes error

### ISSUE THREAD

**Issue by GregTheGreek** [textileio/powergate#369]
```
> ./powd --embedded
2020-04-29T00:46:24.252-0400    FATAL   powd    server/main.go:85       stat /tmp/powergate: no such file or directory
```

### Edit 1
I manually created the directory which got me further, now it seems that it can't connect to the lotus node. Although i presume that at this point `--embedded` may be broken
```
 ./powd --embedded
2020-04-29T00:49:54.144-0400    INFO    powd    server/main.go:112      Current configuration: 
{
  "WalletInitialFunds": {},
  "IpfsAPIAddr": "/ip4/127.0.0.1/tcp/5001",
  "LotusAddress": "/ip4/127.0.0.1/tcp/1234",
  "LotusAuthToken": "",
  "LotusMasterAddr": "",
  "Embedded": true,
  "GrpcHostNetwork": "tcp",
  "GrpcHostAddress": "/ip4/0.0.0.0/tcp/5002",
  "GrpcServerOpts": null,
  "GrpcWebProxyAddress": "0.0.0.0:6002",
  "RepoPath": "/tmp/powergate/.powergate-083355308",
  "GatewayHostAddr": "0.0.0.0:7000"
}
2020-04-29T00:49:54.145-0400    INFO    powd    server/main.go:113      starting server...
2020-04-29T00:49:54.145-0400    ERROR   powd    server/main.go:116      error starting server: connecting to lotus node: dial tcp 127.0.0.1:1234: connect: connection refused
```

system: Ubuntu 19.10 eon

**Comment by jsign** [comment]
@GregTheGreek , you should run the embedded scenario with docker since it needs an IPFS node and a Lotus network also running. You can do that going to the `docker` folder, and running `make embed`. That would run the Powerget server, IPFS node, and Lotus node, so you can use the CLI. It isn't much expected to run `powd --embedded` manually since that needs the assumption that these other deps are already running.

I'm in the process of fixing some things since `interopnet` was changed yesterday, and the embedded network needs the bootstrap peers to be alive.

I'll get back to you here when that is fixed, and I'll add some more explicit indications in the readme to show a complete scenario of how to run the embedded mode with a minimal CLI usage.

**Comment by GregTheGreek** [comment]
Awesome!

Fyi I ran into the same errors running off of the docker, forgot to document that.

**Comment by jsign** [comment]
@GregTheGreek , you can update `master` and follow the steps [here](https://github.com/textileio/powergate#run-in-embedded-mode).
Let me know how that goes!

**Comment by GregTheGreek** [comment]
@jsign I'm still experiencing the same issues, the exact same error is produced (i pruned my docker images and containers as well). It seems because i cannot connect to a Lotus node, `./pow ffs create` is also failing

**Comment by jsign** [comment]
> @jsign I'm still experiencing the same issues, the exact same error is produced (i pruned my docker images and containers as well). It seems because i cannot connect to a Lotus node, `./pow ffs create` is also failing

I've tested those steps in the master branch. Do you mind creating /tmp/powergate folder manually if doesn't exists? I'm not on my laptop now but it may not be created automatically.

After running make embed, do you see the containers running with docker ps?

**Comment by jsign** [comment]
> > @jsign I'm still experiencing the same issues, the exact same error is produced (i pruned my docker images and containers as well). It seems because i cannot connect to a Lotus node, `./pow ffs create` is also failing
> 
> I've tested those steps in the master branch. Do you mind creating /tmp/powergate folder manually if doesn't exists? I'm not on my laptop now but it may not be created automatically.
> 
> After running make embed, do you see the containers running with docker ps?
> 

Also remember that in that setup powd is ran automatically by make. So the tmp folder shouldn't be needed.

**Comment by GregTheGreek** [comment]
What are the docker requirements?

I'm wondering if thats the issue because i see all the containers running

**Comment by jsign** [comment]
I've run in two enviroments.
My laptop:
```bash
~/code/powergate master ❯ docker --version
Docker version 19.03.8, build afacb8b
~/code/powergate master ❯ docker-compose --version
docker-compose version 1.26.0-rc3, build 46118bc5
~/code/powergate master ❯ uname -a
Darwin ignacios-mbp 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
~/code/powergate master ❯
```
An ubuntu cloud VM:
```
ignacio_textile_io@pg-1:~/powergate2$ uname -a
Linux pg-1 5.0.0-1033-gcp #34-Ubuntu SMP Tue Mar 3 04:36:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
ignacio_textile_io@pg-1:~/powergate2$ docker --version
Docker version 19.03.8, build afacb8b7f0
ignacio_textile_io@pg-1:~/powergate2$ docker-compose --version
docker-compose version 1.25.4, build 8d51620a
ignacio_textile_io@pg-1:~/powergate2$ 
```

Can you paste the logs of `make embed`? (that's to say, the interleaved three containers output that starts getting printed by default).

**Comment by GregTheGreek** [comment]
Dump from docker-compose
```
Successfully built 7510e72ff442                                                                                                                                                     [1916/4886]
Successfully tagged embed_powergate:latest                                                                                                                                                     
Creating embed_lotus_1 ... done                                                                                                                                                                
Creating embed_ipfs_1  ... done                                                                                                                                                                
Creating embed_powergate_1 ... done                                                                                                                                                            
Attaching to embed_lotus_1, embed_ipfs_1, embed_powergate_1                                                                                                                                    
ipfs_1       | Changing user to ipfs                                                                                                                                                           
ipfs_1       | ipfs version 0.5.0-rc2                                                                                                                                                          
ipfs_1       | initializing IPFS node at /data/ipfs                                                                                                                                            
ipfs_1       | generating 2048-bit RSA keypair...done                                                                                                                                          
ipfs_1       | peer identity: QmVWMrv82HEZ4uJr8LLgy7jW4q8F7ChbWQNEKVTpbbf7Xs                                                                                                                   
ipfs_1       | to get started, enter:                                                                                                                                                          
ipfs_1       |                                                                                                                                                                                 
ipfs_1       |  ipfs cat /ipfs/QmS4ustL54uo8FzR9455qaxZwuMiUhyvMcX9Ba8nUH4uVv/readme                                                                                                           
ipfs_1       |                                                                                                                                                                                 
ipfs_1       | Initializing daemon...                                                        
ipfs_1       | go-ipfs version: 0.5.0-rc2-b6dfe07                                            
ipfs_1       | Repo version: 9                                                                                                                                                             
ipfs_1       | System version: amd64/linux                                                                                                                                                 
ipfs_1       | Golang version: go1.13.8                                                                                                                                                    
lotus_1      | 2020-04-29T18:04:33.169Z WARN    chainstore      store/store.go:128      no previous chain state found                                                                      
lotus_1      | 2020-04-29T18:04:33.169Z WARN    genesis testing/genesis.go:36   Generating new random genesis block, note that this SHOULD NOT happen unless you are setting up new network    
lotus_1      | init set t3uriwyag64fxcv5p464rrpan4wbnpczbnut6cxvnd5mn3g7yp7w6iq6xevciry7nyknfsmy2mnhfcdz2wuphq t0100                                                                           
lotus_1      | publishing 2 storage deals on miner t01000 with worker t3uriwyag64fxcv5p464rrpan4wbnpczbnut6cxvnd5mn3g7yp7w6iq6xevciry7nyknfsmy2mnhfcdz2wuphq                                   
lotus_1      | Added weight to claim:  2048 2253                                               
lotus_1      | Added weight to claim:  4096 4505                      
lotus_1      | 2020-04-29T18:04:33.172Z INFO    genesis genesis/genesis.go:258  Empty Genesis root: bafy2bzaceaa43et73tgxsoh2xizd4mxhbrcfig4kqp25zfa5scdgkzppllyuu                             
lotus_1      | 2020-04-29T18:04:33.174Z WARN    chainstore      store/store.go:317      no heaviest tipset found, using [bafy2bzacedkn4d5kix3omddejfdcsnibyjbinbpkcwg27yu3c4zuk3xwvpqi6]       
lotus_1      | 2020-04-29T18:04:33.174Z INFO    chainstore      store/store.go:322      New heaviest tipset! [bafy2bzacedkn4d5kix3omddejfdcsnibyjbinbpkcwg27yu3c4zuk3xwvpqi6] (height=0)       
lotus_1      | 2020-04-29T18:04:33.175Z INFO    p2pnode lp2p/addrs.go:114       Swarm listening at: [/ip4/0.0.0.0/tcp/0 /ip6/::/tcp/0]                                                         
lotus_1      | runtime: mlock of signal stack failed: 12                                       
lotus_1      | runtime: increase the mlock limit (ulimit -l) or                                                                                                                                
lotus_1      | runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+                         
lotus_1      | fatal error: mlock failed

lotus_1      |                                                                                                                                                                                 
lotus_1      | runtime stack:                                                                                                                                                                  
lotus_1      | runtime.throw(0x21423bb, 0xc)                                                                                                                                                   
lotus_1      |  /usr/local/go/src/runtime/panic.go:1112 +0x72                                                                                                                                  
lotus_1      | runtime.mlockGsignal(0xc000384000)                                                                                                                                              
lotus_1      |  /usr/local/go/src/runtime/os_linux_x86.go:72 +0x107                                                                                                                            
lotus_1      | runtime.mpreinit(0xc000700380)  
lotus_1      |  /usr/local/go/src/runtime/os_linux.go:341 +0x78                                
lotus_1      | runtime.mcommoninit(0xc000700380)                                               
lotus_1      |  /usr/local/go/src/runtime/proc.go:630 +0x108                                   
lotus_1      | runtime.allocm(0xc000068800, 0x22c92f0, 0x0)                                    
lotus_1      |  /usr/local/go/src/runtime/proc.go:1390 +0x14e                                  
lotus_1      | runtime.newm(0x22c92f0, 0xc000068800)                                           
lotus_1      |  /usr/local/go/src/runtime/proc.go:1704 +0x39                                   
lotus_1      | runtime.startm(0x0, 0xc000066001)                                               
lotus_1      |  /usr/local/go/src/runtime/proc.go:1869 +0x12a                                  
lotus_1      | runtime.wakep(...)              
lotus_1      |  /usr/local/go/src/runtime/proc.go:1953                                         
lotus_1      | runtime.resetspinning()         
lotus_1      |  /usr/local/go/src/runtime/proc.go:2415 +0x93                                   
lotus_1      | runtime.schedule()              
lotus_1      |  /usr/local/go/src/runtime/proc.go:2527 +0x2de                                  
lotus_1      | runtime.goexit0(0xc000488d80)   
lotus_1      |  /usr/local/go/src/runtime/proc.go:2849 +0x1d6                                  
lotus_1      | runtime.mcall(0x800000)         
lotus_1      |  /usr/local/go/src/runtime/asm_amd64.s:318 +0x5b                                
lotus_1      |                                 
lotus_1      | goroutine 1 [runnable]:                                                                                                                                                         
lotus_1      | github.com/jbenet/goprocess/context.CloseAfterContext(0x24ad220, 0xc0000cb020, 0x249a580, 0xc0004bcb40)                                                                         
lotus_1      |  /go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/context/context.go:51 +0x10e                                                                                                    
lotus_1      | github.com/ipfs/go-bitswap.New(0x249a4c0, 0xc0002b0540, 0x24b0e20, 0xc0000dd400, 0x7f6228013198, 0xc0008d9580, 0xc0006bd558, 0x1, 0x1, 0x24bd340, ...)                          
lotus_1      |  /go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.8/bitswap.go:203 +0xfb4                                                                                                            
lotus_1      | github.com/filecoin-project/lotus/node/modules.ChainExchange(0x7f6228012088, 0xc0000c4038, 0x246fbc0, 0xc000127228, 0x24b1aa0, 0xc0008d8e40, 0x24a6760, 0xc0004bc750, 0x7f622801
3128, 0xc0008d9580, ...)                                                                                                                                                                       
lotus_1      |  /go/pkg/mod/github.com/filecoin-project/lotus@v0.2.11-0.20200429011108-559b5e788523/node/modules/chain.go:39 +0x1ed                                                            
lotus_1      | reflect.Value.call(0x1f54b20, 0x22c6328, 0x13, 0x213863d, 0x4, 0xc000138580, 0x5, 0x5, 0x203000, 0x202abe0, ...)                                                                
lotus_1      |  /usr/local/go/src/reflect/value.go:460 +0x8ab                                                                                                                                  
lotus_1      | reflect.Value.Call(0x1f54b20, 0x22c6328, 0x13, 0xc000138580, 0x5, 0x5, 0x10, 0x10, 0xc00023a3a0)                                                                                
lotus_1      |  /usr/local/go/src/reflect/value.go:321 +0xb4                                                                                                                                   
lotus_1      | github.com/filecoin-project/lotus/node.as.func2(0xc000138580, 0x5, 0x5, 0xc000138580, 0xc000512a50, 0x1fcb220)                                                                  
lotus_1      |  /go/pkg/mod/github.com/filecoin-project/lotus@v0.2.11-0.20200429011108-559b5e788523/node/options.go:140 +0xf0                                                                  
lotus_1      | reflect.callReflect(0xc000490390, 0xc0006bdad8, 0xc0006bdac0)                                                                                                                   
lotus_1      |  /usr/local/go/src/reflect/value.go:549 +0x322                                                                                                                                  
lotus_1      | reflect.makeFuncStub(0x7f6228012088, 0xc0000c4038, 0x246fbc0, 0xc000127228, 0x24b1aa0, 0xc0008d8e40, 0x24a6760, 0xc0004bc750, 0x7f6228013128, 0xc0008d9580, ...)                
lotus_1      |  /usr/local/go/src/reflect/asm_amd64.s:20 +0x42                                                                                                                                 
lotus_1      | reflect.Value.call(0x1f54b20, 0xc000490390, 0x13, 0x213863d, 0x4, 0xc000138500, 0x5, 0x5, 0xc0006bddf0, 0x50c138, ...)                                                          
lotus_1      |  /usr/local/go/src/reflect/value.go:460 +0x8ab                                                                                                                                  
lotus_1      | reflect.Value.Call(0x1f54b20, 0xc000490390, 0x13, 0xc000138500, 0x5, 0x5, 0xc000448c40, 0xc000138500, 0x5)                                                                      
lotus_1      |  /usr/local/go/src/reflect/value.go:321 +0xb4                                                                                                                                   
lotus_1      | go.uber.org/dig.(*node).Call(0xc000469860, 0x24a9580, 0xc000448c40, 0x24bd340, 0x1fa9960)                                                                                       
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:665 +0x24a                                                                                                                           
lotus_1      | go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x24bd340, 0x1fa9960, 0x24a9580, 0xc000448c40, 0x1fe4760, 0xc0004dc700, 0x94, ...)                                             
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x353                                                                                                                         
lotus_1      | go.uber.org/dig.paramList.BuildList(0x24bd340, 0x1ef17a0, 0xc00049f1a0, 0x2, 0x2, 0x24a9580, 0xc000448c40, 0xc0006be298, 0x549dbc, 0x10, ...)                                   
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:201 +0xb8                          
lotus_1      | go.uber.org/dig.(*node).Call(0xc0004c6640, 0x24a9580, 0xc000448c40, 0x24bd340, 0x1fe46c0)                                                                                       
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:656 +0xff                            
lotus_1      | go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x24bd340, 0x1fe46c0, 0x24a9580, 0xc000448c40, 0x28, 0xc0004bc390, 0x2050ec0, ...)                                             
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x353                         
lotus_1      | go.uber.org/dig.paramList.BuildList(0x24bd340, 0x1f33fe0, 0xc0004d8fc0, 0x4, 0x4, 0x24a9580, 0xc000448c40, 0xc0006be6c8, 0x549dbc, 0x10, ...)                                   
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:201 +0xb8                          
lotus_1      | go.uber.org/dig.(*node).Call(0xc0004c74a0, 0x24a9580, 0xc000448c40, 0x24bd340, 0x20bd120)                                                                                       
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:656 +0xff                            
lotus_1      | go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x24bd340, 0x20bd120, 0x24a9580, 0xc000448c40, 0x2102640, 0xc00023a088, 0x96, ...)                                             
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x353                         
lotus_1      | go.uber.org/dig.paramList.BuildList(0x24bd340, 0x1f77ea0, 0xc00047be00, 0x6, 0x6, 0x24a9580, 0xc000448c40, 0xc0006beaf8, 0x549dbc, 0x10, ...)                                   
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:201 +0xb8                          
lotus_1      | go.uber.org/dig.(*node).Call(0xc0004c7360, 0x24a9580, 0xc000448c40, 0x24bd340, 0x2100c40)                                                                                       
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:656 +0xff                            
lotus_1      | go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x24bd340, 0x2100c40, 0x24a9580, 0xc000448c40, 0x211de00, 0xc0005140e0, 0x96, ...)                                             
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x353                         
lotus_1      | go.uber.org/dig.paramList.BuildList(0x24bd340, 0x1f346a0, 0xc0004c0940, 0x4, 0x4, 0x24a9580, 0xc000448c40, 0xc0006bef28, 0x549dbc, 0x10, ...)                                   
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:201 +0xb8                          
lotus_1      | go.uber.org/dig.(*node).Call(0xc000469f40, 0x24a9580, 0xc000448c40, 0x24bd340, 0x1f411a0)                                                                                       
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/dig.go:656 +0xff                            
lotus_1      | go.uber.org/dig.paramSingle.Build(0x0, 0x0, 0x0, 0x24bd340, 0x1f411a0, 0x24a9580, 0xc000448c40, 0x2045140, 0xc0004bb460, 0x94, ...)                                             
lotus_1      |  /go/pkg/mod/go.uber.org/dig@v1.8.0/param.go:245 +0x353            
... the same go-routine keeps failing

 goroutine 260 [select]:         
lotus_1      | github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).worker(0xc0004bcea0)                                                                                          
lotus_1      |  /go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.8/internal/decision/blockstoremanager.go:45 +0xda                                                                                  
lotus_1      | github.com/ipfs/go-bitswap/internal/decision.(*blockstoreManager).start.func1(0x24ad220, 0xc0008fd260)                                                                          
lotus_1      |  /go/pkg/mod/github.com/ipfs/go-bitswap@v0.2.8/internal/decision/blockstoremanager.go:38 +0x2a                                                                                  
lotus_1      | github.com/jbenet/goprocess.(*process).Go.func1(0xc00023a750, 0xc0008fd260, 0xc0008fd2c0)                                                                                       
lotus_1      |  /go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:134 +0x3c         
lotus_1      | created by github.com/jbenet/goprocess.(*process).Go                            
lotus_1      |  /go/pkg/mod/github.com/jbenet/goprocess@v0.1.4/impl-mutex.go:133 +0x1f6 

....

powergate_1  | 2020-04-29T18:04:33.891Z INFO    powd    server/main.go:112      Current configuration:                                                                                         
powergate_1  | {                                                                                                                                                                               
powergate_1  |   "WalletInitialFunds": {},                                                                                                                                                     
powergate_1  |   "IpfsAPIAddr": "/dns4/ipfs/tcp/5001",                                                                                                                                         
powergate_1  |   "LotusAddress": "/dns4/lotus/tcp/7777",                                                                                                                                       
powergate_1  |   "LotusAuthToken": "",                                                                                                                                                         
powergate_1  |   "LotusMasterAddr": "",                                                                                                                                                        
powergate_1  |   "Embedded": true,                                                                                                                                                             
powergate_1  |   "GrpcHostNetwork": "tcp",                                                                                                                                                     
powergate_1  |   "GrpcHostAddress": "/ip4/0.0.0.0/tcp/5002",                                                                                                                                   
powergate_1  |   "GrpcServerOpts": null,                                                                                                                                                       
powergate_1  |   "GrpcWebProxyAddress": "0.0.0.0:6002",                                                                                                                                        
powergate_1  |   "RepoPath": "/tmp/powergate/.powergate-081500594",                                                                                                                            
powergate_1  |   "GatewayHostAddr": "0.0.0.0:7000"                                                                                                                                             
powergate_1  | }                                                                                                                                                                               
powergate_1  | 2020-04-29T18:04:33.892Z INFO    powd    server/main.go:113      starting server...                                                                                             
embed_lotus_1 exited with code 2                                                                                                                                                               
powergate_1  | 2020-04-29T18:04:33.942Z ERROR   powd    server/main.go:116      error starting server: connecting to lotus node: lookup lotus on 127.0.0.11:53: no such host                   
ipfs_1       | Swarm listening on /ip4/127.0.0.1/tcp/4001                                                                                                                                      
ipfs_1       | Swarm listening on /ip4/172.18.0.3/tcp/4001                                                                                                                                     
ipfs_1       | Swarm listening on /p2p-circuit                                                                                                                                                 
ipfs_1       | Swarm announcing /ip4/108.174.30.139/tcp/4001                                                                                                                                   
ipfs_1       | Swarm announcing /ip4/127.0.0.1/tcp/4001                                                                                                                                        
ipfs_1       | Swarm announcing /ip4/172.18.0.3/tcp/4001                                                                                                                                       
ipfs_1       | API server listening on /ip4/0.0.0.0/tcp/5001                                                                                                                                   
ipfs_1       | WebUI: http://0.0.0.0:5001/webui                                                                                                                                                
ipfs_1       | Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080                                                                                                                    
ipfs_1       | Daemon is ready                              
powergate_1  | 2020-04-29T18:04:34.857Z INFO    powd    server/main.go:112      Current configuration:                                                                                         
powergate_1  | {                                                                                                                                                                               
powergate_1  |   "WalletInitialFunds": {},                                                                                                                                                     
powergate_1  |   "IpfsAPIAddr": "/dns4/ipfs/tcp/5001",                                                                                                                                         
powergate_1  |   "LotusAddress": "/dns4/lotus/tcp/7777",                                                                                                                                       
powergate_1  |   "LotusAuthToken": "",                                                                                                                                                         
powergate_1  |   "LotusMasterAddr": "",                                                                                                                                                        
powergate_1  |   "Embedded": true,                                                                                                                                                             
powergate_1  |   "GrpcHostNetwork": "tcp",                                                                                                                                                     
powergate_1  |   "GrpcHostAddress": "/ip4/0.0.0.0/tcp/5002",                                                                                                                                   
powergate_1  |   "GrpcServerOpts": null,                                                                                                                                                       
powergate_1  |   "GrpcWebProxyAddress": "0.0.0.0:6002",                                                                                                                                        
powergate_1  |   "RepoPath": "/tmp/powergate/.powergate-490390597",                                                                                                                            
powergate_1  |   "GatewayHostAddr": "0.0.0.0:7000"                                                                                                                                             
powergate_1  | }                                                                                                                                                                               
powergate_1  | 2020-04-29T18:04:34.857Z INFO    powd    server/main.go:113      starting server...                                                                                             
powergate_1  | 2020-04-29T18:04:34.891Z ERROR   powd    server/main.go:116      error starting server: connecting to lotus node: lookup lotus on 127.0.0.11:53: no such host                   
embed_powergate_1 exited with code 255         
powergate_1  | 2020-04-29T18:04:35.917Z INFO    powd    server/main.go:112      Current configuration:                                                                                         
powergate_1  | {                               
powergate_1  |   "WalletInitialFunds": {},     
powergate_1  |   "IpfsAPIAddr": "/dns4/ipfs/tcp/5001",                                         
powergate_1  |   "LotusAddress": "/dns4/lotus/tcp/7777",                                       
powergate_1  |   "LotusAuthToken": "",         
powergate_1  |   "LotusMasterAddr": "",        
powergate_1  |   "Embedded": true,             
powergate_1  |   "GrpcHostNetwork": "tcp",     
powergate_1  |   "GrpcHostAddress": "/ip4/0.0.0.0/tcp/5002",                                   
powergate_1  |   "GrpcServerOpts": null,       
powergate_1  |   "GrpcWebProxyAddress": "0.0.0.0:6002",                                        
powergate_1  |   "RepoPath": "/tmp/powergate/.powergate-379592053",                            
powergate_1  |   "GatewayHostAddr": "0.0.0.0:7000"                                             
powergate_1  | }                               
powergate_1  | 2020-04-29T18:04:35.917Z INFO    powd    server/main.go:113      starting server...                                                                                             
powergate_1  | 2020-04-29T18:04:35.954Z ERROR   powd    server/main.go:116      error starting server: connecting to lotus node: lookup lotus on 127.0.0.11:53: no such host                   
embed_powergate_1 exited with code 255 
```

**Comment by jsign** [comment]
Yes, it can't connect since the lotus node is failing.

In the logs says:
```
lotus_1      | runtime: mlock of signal stack failed: 12                                       
lotus_1      | runtime: increase the mlock limit (ulimit -l) or                                                                                                                                
lotus_1      | runtime: update your kernel to 5.3.15+, 5.4.2+, or 5.5+   
```
Docker depends on your kernel version or configuration to run containers.
You may try with the `ulimit -l` suggestion... I wouldn't expect you to update your kernel version. :) 

I asked @asutula to double check if in his laptop things are running correctly, and they're. So it must be that kernel configuration that is on our way.

**Comment by jsign** [comment]
@GregTheGreek , I'll be closing this issue since doesn't seem to be PG related. Feel free to open a new one if you discover something further!
