### ISSUE TITLE
Fails to Make Deal with Error Not Enough Miners from Reputation Module to Satisfy The Constraints Error

### ISSUE THREAD

**Issue by ChristianOConnor** [textileio/powergate#852]
I am running WSL Ubuntu 20.04 (Version 2 with Docker Desktop Support) within Windows 10 Pro Version 21H1  
  
The steps are as follows:  
1) `git clone https://github.com/textileio/powergate.git`  
2) `cd powergate/`  
3) `cd docker/`  
4) `nano docker-compose.yaml` where I added "["lotus", "daemon", "--import-snapshot", "https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car"]" between lines 32 and 33.  
5) `make up`  
6) Waited for the node to finish importing and then syncing.  
7) `^C` then `make down` then deleted the line "["lotus", "daemon", "--import-snapshot", "https://fil-chain-snapshots-fallback.s3.amazonaws.com/mainnet/minimal_finality_stateroots_latest.car"]" from docker-compose.yaml  
8) `make up`  
9) Now that the node was running I typed `cd ..` so I was in the repo's root directory, then `make install-pow`  
10) with the `pow` command in my GOPATH I typed `pow` to make sure pow was linked fine to `powd`. It was.  
11) `pow admin users create`  
12) copied the token and ran `export POW_TOKEN=<token copied to here>`  
13) Then `pow wallet addrs` and funded the address  
14) I went to the directory behind the folder of my static website which is about 5GB in size.  
15) I typed `pow data stage <my-static-site-folder>`  
16) After it was finished staging and printed out the CID I typed `pow config apply --watch <CID` waited a long time while it said the job was executing and then I got...  
  
```
---------------------------------------+--------------------------------+-------+-------+--------------
             <job id here>             | JOB_STATUS_FAILED executing    |       |       |
                                       | cold-storage config: making    |       |       |
                                       | deal configs: getting miners   |       |       |
                                       | from minerselector: getting    |       |       |
                                       | miners from reputation         |       |       |
                                       | module: not enough miners from |       |       |
                                       | reputation module to satisfy   |       |       |
                                       | the constraints                |       |       |
```
  
I don't understand what the problem is. I repeated the `pow config apply --watch <CID` command each time adding the --override flag with several different modifications to a custom config file. The content did appear briefly on IPFS (not Filecoin), but after I continued running the config apply command the site went down from IPFS.  
  
Here are my powergate logs.  
```
<myusername>@<mycomputername>:~/dev/powergate_config_files$ docker logs mainnet_powergate_1
2021-07-26T09:04:20.618Z        INFO    powd    powd/main.go:57 starting powd:
        version:        git
        build date:     2021-07-26T07:45:07Z
        git summary:    v2.6.2-dirty
        git branch:     master
        git commit:     34dc0fe
        git state:      dirty
2021-07-26T09:04:20.619Z        INFO    powd    powd/main.go:72 {
  "RepoPath": "/root/powergate/.powergate",
  "MaxMindDBFolder": ".",
  "Devnet": false,
  "IpfsAPIAddr": "/dns4/ipfs/tcp/5001",
  "LotusAddress": "/dns4/lotus/tcp/1234",
  "LotusAuthToken": "<LotusAuthTokenHere>",
  "LotusMasterAddr": "",
  "LotusConnectionRetries": 180,
  "GrpcHostNetwork": "tcp",
  "GrpcHostAddress": "/ip4/0.0.0.0/tcp/5002",
  "GrpcServerOpts": null,
  "GrpcWebProxyAddress": "0.0.0.0:6002",
  "GatewayBasePath": "/",
  "GatewayHostAddr": "0.0.0.0:7000",
  "IndexRawJSONHostAddr": "0.0.0.0:8889",
  "MongoURI": "",
  "MongoDB": "",
  "FFSAdminToken": "",
  "FFSUseMasterAddr": false,
  "FFSDealFinalityTimeout": 259200000000000,
  "FFSMinimumPieceSize": 67108864,
  "FFSRetrievalNextEventTimeout": 3600000000000,
  "FFSMaxParallelDealPreparing": 2,
  "FFSGCAutomaticGCInterval": 3600000000000,
  "FFSGCStageGracePeriod": 3600000000000,
  "SchedMaxParallel": 1000,
  "MinerSelector": "reputation",
  "MinerSelectorParams": "",
  "DealWatchPollDuration": 900000000000,
  "AutocreateMasterAddr": false,
  "WalletInitialFunds": {},
  "AskIndexQueryAskTimeout": 15000000000,
  "AskindexMaxParallel": 3,
  "AskIndexRefreshInterval": 21600000000000,
  "AskIndexRefreshOnStart": false,
  "IndexMinersRefreshOnStart": false,
  "IndexMinersOnChainMaxParallel": 20,
  "IndexMinersOnChainFrequency": 21600000000000,
  "DisableIndices": false,
  "DisableNonCompliantAPIs": false
}
2021-07-26T09:04:20.619Z        INFO    powd    powd/main.go:75 starting server...
2021-07-26T09:04:20.620Z        WARN    lotus-client    lotus/client.go:50      failed to connect to Lotus client dial tcp 172.20.0.3:1234: connect: connection refused, retrying...
2021-07-26T09:04:30.621Z        WARN    lotus-client    lotus/client.go:50      failed to connect to Lotus client dial tcp 172.20.0.3:1234: connect: connection refused, retrying...
2021-07-26T09:04:40.622Z        WARN    lotus-client    lotus/client.go:50      failed to connect to Lotus client dial tcp 172.20.0.3:1234: connect: connection refused, retrying...
2021-07-26T09:04:50.626Z        INFO    server  server/server.go:196    Detected Lotus node connected to network: mainnet
2021-07-26T09:05:03.233Z        INFO    fchost  fchost/fchost.go:116    connected to 11 out of 15 bootstrap peers
2021-07-26T09:05:03.233Z        INFO    fchost  fchost/fchost.go:60     bootstraping libp2p host dht
2021-07-26T09:05:03.233Z        INFO    fchost  fchost/fchost.go:64     dht bootstraped!
2021-07-26T09:05:03.233Z        INFO    server  server/server.go:684    Ensuring migrations...
2021-07-26T09:05:03.233Z        INFO    server  server/server.go:595    Opening badger database...
2021-07-26T09:05:03.237Z        INFO    migrations      migration/migration.go:67       Current datastore version is 5, target version 5
2021-07-26T09:05:03.237Z        INFO    server  server/server.go:699    Migrations ensured
2021-07-26T09:05:03.239Z        INFO    server  server/server.go:595    Opening badger database...
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:217    Wiring internal components...
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:229    Starting ask index...
2021-07-26T09:05:03.247Z        INFO    index-ask       runner/runner.go:65     loaded persisted index with 0 entries
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:235    Starting miner index...
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:247    Starting faults index...
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:256    Starting deals module...
2021-07-26T09:05:03.247Z        INFO    deals   module/module.go:51     creating deal watcher
2021-07-26T09:05:03.247Z        INFO    deals   module/module.go:66     resuming pending records
2021-07-26T09:05:03.247Z        INFO    deals   module/records.go:170   resuming 0 pending records
2021-07-26T09:05:03.247Z        INFO    deals   module/records.go:179   resumed watching 0 pending storage deal records
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:262    Starting wallet module...
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:291    Starting FFS scheduler...
2021-07-26T09:05:03.247Z        INFO    reputation      reputation/reputation.go:200    rebuilding index
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:307    Starting gRPC, gateway and index HTTP servers...
2021-07-26T09:05:03.247Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 0
2021-07-26T09:05:03.247Z        INFO    reputation      reputation/reputation.go:227    built scores for 0 miners in 0ms
2021-07-26T09:05:03.247Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 0
2021-07-26T09:05:03.247Z        INFO    server  server/server.go:366    Starting IPFS reverse proxy...
2021-07-26T09:05:03.248Z        INFO    deals-watcher   dealwatcher/dealwatcher.go:144  deal watcher created
2021-07-26T09:05:03.248Z        INFO    server  server/server.go:355    Starting finished, serving requests
2021-07-26T09:05:03.248Z        INFO    powd    powd/main.go:80 server started.
2021-07-26T09:06:50.631Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 367
2021-07-26T09:08:50.638Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 352
2021-07-26T09:10:50.642Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 325
2021-07-26T09:12:50.645Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 277
2021-07-26T09:14:50.650Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 239
2021-07-26T09:16:50.654Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 191
2021-07-26T09:18:50.662Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 142
2021-07-26T09:20:50.668Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 103
2021-07-26T09:22:50.671Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 54
2021-07-26T09:24:50.676Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 370, todo: 8
2021-07-26T09:26:50.681Z        WARN    lotus-client    lotus/metrics.go:90     Louts behind in syncing with height diff 39, todo: 7
2021-07-26T10:05:03.251Z        INFO    ffs-scheduler   scheduler/scheduler.go:208      running scheduler gc...
2021-07-26T10:05:03.259Z        INFO    ffs-scheduler   scheduler/scheduler.go:236      scheduler gc ran with 0 excluded cids, unpinning 0 staged cids
2021-07-26T10:35:18.496Z        INFO    ffs-manager     manager/manager.go:109  creating instance
2021-07-26T10:35:18.528Z        INFO    ffs-auth        auth/auth.go:38 generating auth-token for instance <instanceIdHere>
2021-07-26T11:00:21.977Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Pushing new configuration...
2021-07-26T11:00:21.995Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Configuration saved successfully
2021-07-26T11:00:21.995Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 1, total executing: 0
2021-07-26T11:00:22.005Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 1
2021-07-26T11:00:22.006Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Executing job <JobIdHere>...
2021-07-26T11:00:22.009Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Automatically staging Cid from the IPFS network...
2021-07-26T11:00:22.019Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Executing Cold-Storage configuration...
2021-07-26T11:00:22.022Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Current replication factor is lower than desired, making 1 new deals...
2021-07-26T11:00:22.024Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Entering deal preprocessing queue...
2021-07-26T11:00:22.026Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Calculating piece size...
2021-07-26T11:01:36.270Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       The payload size is 5.1 GiB, and the calculated piece size is 8.0 GiB
2021-07-26T11:01:36.278Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Starting deals failed, with cause: making deal configs: getting miners from minerselector: getting miners from reputation module: not enough miners from reputation module to satisfy the constraints
2021-07-26T11:01:36.280Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Cold-Storage execution failed.
2021-07-26T11:01:36.282Z        ERROR   ffs-scheduler   scheduler/scheduler.go:531      executing job <JobIdHere>: executing cold-storage config: making deal configs: getting miners from minerselector: getting miners from reputation module: not enough miners from reputation module to satisfy the constraints
2021-07-26T11:01:36.285Z        INFO    ffs-sched-sjstore       sjstore/sjstore.go:702  notifying watcher
2021-07-26T11:01:36.285Z        INFO    ffs-cidlogger   joblogger/joblogger.go:53       Job <JobIdHere> execution failed: executing cold-storage config: making deal configs: getting miners from minerselector: getting miners from reputation module: not enough miners from reputation module to satisfy the constraints
2021-07-26T11:01:36.287Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 0
2021-07-26T11:01:36.288Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 0
2021-07-26T11:01:36.288Z        INFO    ffs-scheduler   scheduler/scheduler.go:353      storage job total queued: 0, total executing: 0
<myusername>@<mycomputername>:~/dev/powergate_config_files$
```  
  
Here are my IPFS logs:  
```
<myusername>@<mycomputername>:~/dev/powergate_config_files$ docker logs mainnet_ipfs_1
Changing user to ipfs
ipfs version 0.7.0
Found IPFS fs-repo at /data/ipfs
Initializing daemon...
go-ipfs version: 0.7.0-ea77213
Repo version: 10
System version: amd64/linux
Golang version: go1.14.4
Swarm listening on /ip4/127.0.0.1/tcp/4001
Swarm listening on /ip4/127.0.0.1/udp/4001/quic
Swarm listening on /ip4/172.20.0.2/tcp/4001
Swarm listening on /ip4/172.20.0.2/udp/4001/quic
Swarm listening on /p2p-circuit
Swarm announcing /ip4/127.0.0.1/tcp/4001
Swarm announcing /ip4/127.0.0.1/udp/4001/quic
Swarm announcing /ip4/172.20.0.2/tcp/4001
Swarm announcing /ip4/172.20.0.2/udp/4001/quic
Swarm announcing /ip4/68.80.241.181/udp/55230/quic
API server listening on /ip4/0.0.0.0/tcp/5001
WebUI: http://0.0.0.0:5001/webui
Gateway (readonly) server listening on /ip4/0.0.0.0/tcp/8080
Daemon is ready
<myusername>@<mycomputername>:~/dev/powergate_config_files$
```  
  
Please let me know what the problem is, I really love Filecoin and Powergate and want to take part in the ecosystem.

**Comment by jsign** [comment]
The problem here is that you're relying on the default behavior of auto-miner selection, which is brittle if your miner-index part of the system hasn't built the index or the safe values used for deal making (e.g: price) doesn't match whatever is available.

Miner selection is a hard problem in general, but the only way to avoid this problem is that you provide the miners you want to store the data with using the `TrustedMiner` (https://docs.textile.io/powergate/storageconfig). That will try first with the miners you specified there. You could `pow config default > def.config`, then edit `def.config`, and then `pow config set-default` to set it as the default, so your next `pow apply` can use it and try targeting better miners.

From where you would get miners to set that field? Is a tricky question. You can use Filfox to try finding some miners, or joining #powergate-users in the Lotus slack channel to see if anyone from the community can share miners that they're using now and are working.

**Comment by ChristianOConnor** [comment]
Thank you so much! This is excellent it looks like the deal is going through. I looked up miners with a high reputation score in North America on https://filrep.io/ and added them to the trusted miners section of the config json file. It looks like it made a deal but the process appears to be hanging on "StorageDealTransferring" I'm assuming it's uploading my directory to the miner right?

**Comment by ChristianOConnor** [comment]
It's still not working... After all this lol. It is stuck on `StorageDealCheckForAcceptance`. It's just hangs there. I killed the process because I used the `--watch` flag when I did the deal command. Here is the output that was hanging for the deal creation command:  
  
```
                 JOB ID                |        STATUS        |  MINER   |    PRICE     |          DEAL STATUS
---------------------------------------+----------------------+----------+--------------+--------------------------------
              <Job Id Here>            | JOB_STATUS_EXECUTING |          |              |
                                       |                      | <miner>  | 800000000000 | StorageDealCheckForAcceptance
```  
  
When I ran `pow storage-job watch <CID of Directory>`, I got this:  
  
```
                            JOB ID                            |     STATUS     | MINER | PRICE | DEAL STATUS
--------------------------------------------------------------+----------------+-------+-------+--------------
               <CID of The Actual Directory>                  | awaiting state |       |       |
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x<hex string here> pc=0x<hexstringhere>]

goroutine 1 [running]:
github.com/textileio/powergate/v2/cmd/pow/common.WatchJobIds(0x<Hex string here>, 0x1, 0x1)
        /home/warpanomalythree/dev/powergate/cmd/pow/common/common.go:110 +0x41a
github.com/textileio/powergate/v2/cmd/pow/cmd/storagejobs/watch.glob..func2(0x<Hex string here>, 0x<Hex string here>, 0x1, 0x1)
        /home/warpanomalythree/dev/powergate/cmd/pow/cmd/storagejobs/watch/watch.go:23 +0x<Hex string here>
github.com/spf13/cobra.(*Command).execute(0x<Hex string here>, 0x<Hex string here>, 0x1, 0x1, 0x<Hex string here>, 0x<Hex string here>)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x<Hex string here>
github.com/spf13/cobra.(*Command).ExecuteC(0x<Hex string here>, 0x<Hex string here>, 0x<Hex string here>, 0x<Hex string here>)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x<Hex string here>
github.com/spf13/cobra.(*Command).Execute(...)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/warpanomalythree/dev/powergate/cmd/pow/main.go:11 +0x<Hex string here>
```

**Comment by ChristianOConnor** [comment]
Also, this is the output of `pow storage-job list` for the relevant job:  
```
"storageJobs":  [
    {
      "id":  "<This Job's Id>",
      "apiId":  "<Id string I don't recoignize>",
      "cid":  "<File Directory's CID>",
      "status":  "JOB_STATUS_EXECUTING",
      "errorCause":  "",
      "dealInfo":  [
        {
          "proposalCid":  "<CID I don't recognize>",
          "stateId":  "29",
          "stateName":  "StorageDealAwaitingPreCommit",
          "miner":  "<Miner Id>",
          "pieceCid":  "<Hex String I Don't Recognize>",
          "size":  "8522825728",
          "pricePerEpoch":  "800000000000",
          "startEpoch":  "0",
          "duration":  "523192",
          "dealId":  "<Number Here>",
          "activationEpoch":  "0",
          "message":  ""
        }
      ],
      "dealErrors":  [],
      "createdAt":  "<Number Here>"
    },
```  
  
One more thought... Could my problem be that the directory to be stored is too big? I have one file in the directory that's about 5GB.

**Comment by jsign** [comment]
Actually, things are going pretty well for you (apart from that CLI panic, but looks like hasn't stopped you from moving further).

Both `StorageDealCheckForAcceptance` and  `StorageDealAwaitingPreCommit` are expected states of deals that can take a long time to go through, in the order of hours. A Filecoin deal can take one or even two days depending on the miner to be totally confirmed. 

So, it isn't really stuck but those states are really the expected ones and the transitions take hours. That fact doesn't depend on Powergate (or any Filecoin client), is just the way that the network works since miners have to do many things from receiving your proposal until the data gets fully confirmed (packing, publishing, sealing, proving).

**Comment by ChristianOConnor** [comment]
> Actually, things are going pretty well for you (apart from that CLI panic, but looks like hasn't stopped you from moving further).
> 
> Both `StorageDealCheckForAcceptance` and `StorageDealAwaitingPreCommit` are expected states of deals that can take a long time to go through, in the order of hours. A Filecoin deal can take one or even two days depending on the miner to be totally confirmed.
> 
> So, it isn't really stuck but those states are really the expected ones and the transitions take hours. That fact doesn't depend on Powergate (or any Filecoin client), is just the way that the network works since miners have to do many things from receiving your proposal until the data gets fully confirmed (packing, publishing, sealing, proving).

Oh that's good to know. I'm glad it's actually going well. So if I just leave my powergate docker stack running for a few more days it will upload the files to the miner and the deal will go through? And the powergate stack will automatically stream upload the files to the miner? Is there any command to check if the file has been uploaded to the miner yet?

Btw one more thing, how do I back up my wallet's private key? I can't seem to find the `.powergate` directory to get the file that contains my wallet's private key. I am running this as the docker mainnet version.

**Comment by jsign** [comment]
> Oh that's good to know. I'm glad it's actually going well. So if I just leave my powergate docker stack running for a few more days it will upload the files to the miner and the deal will go through? And the powergate stack will automatically stream upload the files to the miner? Is there any command to check if the file has been uploaded to the miner yet?
 
Yes, everything needed is done by Powergate to store the data in the miner. Things can fail in general mostly due to failed transfers, or the miner having some problem for some reason. The way you know how things are going are mostly checking the status of the Job that will switch from _executing_ to _successful_ (if all went well), or `pow data log <cid>` to see the log stream too.

> Btw one more thing, how do I back up my wallet's private key? I can't seem to find the .powergate directory to get the file that contains my wallet's private key. I am running this as the docker mainnet version.

The private keys only live in the Lotus node, so if you want to export it, you need to `docker run` inside the Lotus container and `lotus wallet export` it.

**Comment by ChristianOConnor** [comment]
I'm glad it appears to be working. This is the output of `pow data log <CID of The Actual Directory>` :  
```
> 2021-07-26T07:00:21 - Pushing new configuration...
> 2021-07-26T07:00:21 - Configuration saved successfully
> 2021-07-26T07:00:22 - Executing job <CID of Previous Failed Job>...
> 2021-07-26T07:00:22 - Automatically staging Cid from the IPFS network...
> 2021-07-26T07:00:22 - Executing Cold-Storage configuration...
> 2021-07-26T07:00:22 - Current replication factor is lower than desired, making 1 new deals...
> 2021-07-26T07:00:22 - Entering deal preprocessing queue...
> 2021-07-26T07:00:22 - Calculating piece size...
> 2021-07-26T07:01:36 - The payload size is 5.1 GiB, and the calculated piece size is 8.0 GiB
> 2021-07-26T07:01:36 - Starting deals failed, with cause: making deal configs: getting miners from minerselector: getting miners from reputation module: not enough miners from reputation module to satisfy the constraints
> 2021-07-26T07:01:36 - Cold-Storage execution failed.
> 2021-07-26T07:01:36 - Job <CID of Previous Failed Job> execution failed: executing cold-storage config: making deal configs: getting miners from minerselector: getting miners from reputation module: not enough miners from reputation module to satisfy the constraints
> 2021-07-26T22:56:03 - Pushing new configuration...
> 2021-07-26T22:56:03 - Configuration saved successfully
> 2021-07-26T22:56:03 - Executing job <CID of Second Previous Failed Job>...
> 2021-07-26T22:56:03 - Automatically staging Cid from the IPFS network...
> 2021-07-26T22:56:07 - Executing Cold-Storage configuration...
> 2021-07-26T22:56:07 - Current replication factor is lower than desired, making 1 new deals...
> 2021-07-26T22:56:07 - Entering deal preprocessing queue...
> 2021-07-26T22:56:07 - Calculating piece size...
> 2021-07-26T22:57:15 - The payload size is 5.1 GiB, and the calculated piece size is 8.0 GiB
> 2021-07-26T22:57:16 - Proposing deal to miner <MinerId> with 0.0000001 FIL per epoch...
> 2021-07-26T22:57:16 - Watching deals unfold...
> 2021-07-26T22:57:16 - Deal with miner <MinerId> changed state to StorageDealReserveClientFunds
> 2021-07-26T22:57:19 - DealID 0 with miner <MinerId> failed and won't be active on-chain: adding market funds failed: GasEstimateMessageGas error: estimating gas used: message execution failed: exit SysErrInsufficientFunds(6), reason: failed to transfer funds (RetCode=6): transfer failed when deducting funds (0.418604 FIL): not enough funds (RetCode=6)
> 2021-07-26T22:57:19 - Cold-Storage execution failed.
> 2021-07-26T22:57:19 - Job <CID of Second Previous Failed Job> execution failed: executing cold-storage config: all started deals failed
> 2021-07-26T23:27:45 - Pushing new configuration...
> 2021-07-26T23:27:45 - Configuration saved successfully
> 2021-07-26T23:27:45 - Executing job <This Suceeded Job's Id>...
> 2021-07-26T23:27:45 - Automatically staging Cid from the IPFS network...
> 2021-07-26T23:27:45 - Executing Cold-Storage configuration...
> 2021-07-26T23:27:45 - Current replication factor is lower than desired, making 1 new deals...
> 2021-07-26T23:27:45 - Entering deal preprocessing queue...
> 2021-07-26T23:27:45 - Calculating piece size...
> 2021-07-26T23:28:53 - The payload size is 5.1 GiB, and the calculated piece size is 8.0 GiB
> 2021-07-26T23:28:54 - Proposing deal to miner <MinerId> with 0.0000001 FIL per epoch...
> 2021-07-26T23:28:54 - Watching deals unfold...
> 2021-07-26T23:28:54 - Deal with miner <MinerId> changed state to StorageDealReserveClientFunds
> 2021-07-26T23:32:30 - Deal with miner <MinerId> changed state to StorageDealClientFunding
> 2021-07-26T23:32:31 - Deal with miner <MinerId> changed state to StorageDealFundsReserved
> 2021-07-26T23:32:31 - Deal with miner <MinerId> changed state to StorageDealTransferring
> 2021-07-27T01:02:08 - Deal with miner <MinerId> changed state to StorageDealCheckForAcceptance
> 2021-07-27T02:29:31 - Deal with miner <MinerId> changed state to StorageDealProposalAccepted
> 2021-07-27T04:22:45 - Executing job <This Suceeded Job's Id>...
> 2021-07-27T04:22:45 - Automatically staging Cid from the IPFS network...
> 2021-07-27T04:22:45 - Executing Cold-Storage configuration...
> 2021-07-27T04:22:45 - Resuming 1 dettached executing deals...
> 2021-07-27T04:22:45 - Watching deals unfold...
> 2021-07-27T04:22:45 - Deal <Number> with miner <MinerId> changed state to StorageDealAwaitingPreCommit
> 2021-07-27T15:35:55 - Executing job <This Suceeded Job's Id>...
> 2021-07-27T15:35:55 - Automatically staging Cid from the IPFS network...
> 2021-07-27T15:35:55 - Executing Cold-Storage configuration...
> 2021-07-27T15:35:55 - Resuming 1 dettached executing deals...
> 2021-07-27T15:35:55 - Watching deals unfold...
> 2021-07-27T15:35:55 - Deal <Number> with miner <MinerId> changed state to StorageDealAwaitingPreCommit
> 2021-07-27T16:33:24 - Deal <Number> with miner <MinerId> is active on-chain
> 2021-07-27T16:33:25 - A total of 1 resumed deals finished successfully
> 2021-07-27T16:33:25 - The current replication factor is equal or higher than desired, avoiding making new deals.
> 2021-07-27T16:33:25 - Cold-Storage configuration ran successfully.
> 2021-07-27T16:33:25 - Executing Hot-Storage configuration...
> 2021-07-27T16:33:25 - Data was unpinned.
> 2021-07-27T16:33:25 - Hot-Storage configuration ran successfully.
> 2021-07-27T16:33:25 - Job <This Suceeded Job's Id> execution finished with status Success.
```  
  
I still get the following error when I type `pow storage-job watch <CID of The Actual Directory>` :  
```
                            JOB ID                            |     STATUS     | MINER | PRICE | DEAL STATUS
--------------------------------------------------------------+----------------+-------+-------+--------------
  bafybeianuktguheyxwxowjw6htnwn5xeedtrmlspnml3mc7sjud4aoweuy | awaiting state |       |       |
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0xc573da]

goroutine 1 [running]:
github.com/textileio/powergate/v2/cmd/pow/common.WatchJobIds(0xc0004a4f10, 0x1, 0x1)
        /home/warpanomalythree/dev/powergate/cmd/pow/common/common.go:110 +0x41a
github.com/textileio/powergate/v2/cmd/pow/cmd/storagejobs/watch.glob..func2(0x208ee20, 0xc0004a4260, 0x1, 0x1)
        /home/warpanomalythree/dev/powergate/cmd/pow/cmd/storagejobs/watch/watch.go:23 +0x8e
github.com/spf13/cobra.(*Command).execute(0x208ee20, 0xc0004a4240, 0x1, 0x1, 0x208ee20, 0xc0004a4240)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x2086ea0, 0xc000084778, 0xc00036bf78, 0x406365)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/warpanomalythree/golibs/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/warpanomalythree/dev/powergate/cmd/pow/main.go:11 +0x31
```  
  
Why am I still getting this error? Shouldn't it change from `awaiting state` to `success` or something? Maybe I just need to wait a little longer...  
  
Again so sorry to bother and I really appreciate your help but can you tell me the exact command to backup my wallet? This is actually the first time I've ever used docker so I'm not too familiar with how to get inside the actual docker image. Thanks again for the help, I'm sorry to bother you.

**Comment by jsign** [comment]
No problem, I'm happy you got your data on-chain... that's an important milestone!

Reg the CLI error, not sure yet bue needs some attention. Looks like is from the CLI side, so shouldn't be something too bad.

Reg your wallet backup, you should do:
1. `docker exec -it testnet_lotus_1 /bin/sh`
2. `lotus wallet list`
3. `lotus wallet export <wallet-addrs-you-want>`
Then you'll see some hexadecimal output which is the private key. That same value you can use with `lotus wallet import` in other Lotus node.

**Comment by ChristianOConnor** [comment]
Okay awesome it looks like my initial issue of not being able to have a deal go through was solved. The thing that solved it was going to a filecoin miner info aggregation site (I used "https://filrep.io/") and adding miners to the `TrustedMiner` section of the config file used in the `apply` command to start a Filecoin deal.  
  
Also, as a bonus, the below comment solved the issue of how to back up the private key of you address used with powergate.

> No problem, I'm happy you got your data on-chain... that's an important milestone!
> 
> Reg the CLI error, not sure yet bue needs some attention. Looks like is from the CLI side, so shouldn't be something too bad.
> 
> Reg your wallet backup, you should do:
> 
>     1. `docker exec -it testnet_lotus_1 /bin/sh`
> 
>     2. `lotus wallet list`
> 
>     3. `lotus wallet export <wallet-addrs-you-want>`
>        Then you'll see some hexadecimal output which is the private key. That same value you can use with `lotus wallet import` in other Lotus node.
